### PR TITLE
automation script for folder and file creation

### PR DESCRIPTION
**Pull request by kunal266**
Hey there 
As described, the code to create the folders for state and county with .gitkeep file inside the counties' folders
hope you accept the request
It was fun working this Task

### CODE REVIEW

**Comment by banjtheman** [comment]
Thoughts on why the script misses Hawaii and  Delaware?
Otherwise works great!!

```

(base) banjtheman@ubuntu]counties(main|?)> ls data/ | wc -l
48

(base) [banjtheman@ubuntu]data(main|?)> ls
 Alabama   Arkansas     Connecticut   Idaho      Iowa       Louisiana   Massachusetts   Mississippi   Nebraska        'New Jersey'  'North Carolina'   Oklahoma      'Puerto Rico'      Tennessee   Vermont     'West Virginia'
 Alaska    California   Florida       Illinois   Kansas     Maine       Michigan        Missouri      Nevada          'New Mexico'  'North Dakota'     Oregon        'South Carolina'   Texas       Virginia     Wisconsin
 Arizona   Colorado     Georgia       Indiana    Kentucky   Maryland    Minnesota       Montana      'New Hampshire'  'New York'     Ohio              Pennsylvania  'South Dakota'     Utah        Washington   Wyoming
```

**Comment by kunal266** [comment]
I apologise , I will clear the issue as soon as possible

**Comment by kunal266** [comment]
Hawaii and Delaware issues is fixed, counties folder contains the data folder, with all the States and Counties

**Comment by banjtheman** [comment]
remove the data folder for the pr

**Comment by banjtheman** [comment]
remove the READMEs then its good to go

**Pull request merged**
